// <auto-generated />
using System;
using LogicLevel;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LogicLevel.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "823365c1-98fd-41b8-8b82-a4aa8f2b7901",
                            ConcurrencyStamp = "d3ce6efc-2d70-47cc-a599-4a9f9f8b9331",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "91a2f26d-b11e-4f60-b249-517fc7c096a6",
                            ConcurrencyStamp = "3d537b1f-f702-462a-bc76-7940ecac2935",
                            Name = "User",
                            NormalizedName = "USER"
                        },
                        new
                        {
                            Id = "c0a93be2-a5e7-4116-97ba-1f01d875950c",
                            ConcurrencyStamp = "ffc62f96-c046-4646-a2cd-e5a88b3839e4",
                            Name = "Second-Admin",
                            NormalizedName = "SECOND-ADMIN"
                        },
                        new
                        {
                            Id = "c0a93be2-a5e7-4116-97ba-1f01d875952c",
                            ConcurrencyStamp = "900cc264-c620-47d2-ab1a-76a8da6c6eeb",
                            Name = "Services Provider",
                            NormalizedName = "SERVICES PROVIDER"
                        },
                        new
                        {
                            Id = "cf36f71b-1ff9-45ad-9b3f-636c53967b9c",
                            ConcurrencyStamp = "a30e3670-55f0-4ed4-bd35-7ad508552b95",
                            Name = "Super-Admin",
                            NormalizedName = "SUPER-ADMIN"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ProjectDataStructure.Addressrelatedclasses.IndiaCity", b =>
                {
                    b.Property<int>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CityId"));

                    b.Property<string>("CityName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("indiastate")
                        .HasColumnType("int");

                    b.HasKey("CityId");

                    b.ToTable("IndiaCities");

                    b.HasData(
                        new
                        {
                            CityId = 1,
                            CityName = "Ahmedabad",
                            indiastate = 6
                        },
                        new
                        {
                            CityId = 2,
                            CityName = "Gandhinagar",
                            indiastate = 6
                        },
                        new
                        {
                            CityId = 3,
                            CityName = "Chandkheda",
                            indiastate = 6
                        },
                        new
                        {
                            CityId = 4,
                            CityName = "Pethapur",
                            indiastate = 6
                        },
                        new
                        {
                            CityId = 5,
                            CityName = "Randheja",
                            indiastate = 6
                        },
                        new
                        {
                            CityId = 6,
                            CityName = "Rupal",
                            indiastate = 6
                        },
                        new
                        {
                            CityId = 7,
                            CityName = "Adalaj",
                            indiastate = 6
                        },
                        new
                        {
                            CityId = 8,
                            CityName = "Kalol",
                            indiastate = 6
                        });
                });

            modelBuilder.Entity("ProjectDataStructure.Addressrelatedclasses.IndiaUserAddress", b =>
                {
                    b.Property<int>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AddressId"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("Zipcode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AddressId");

                    b.HasIndex("CityId");

                    b.ToTable("IndianUserAddresses");
                });

            modelBuilder.Entity("ProjectDataStructure.Electronics.ServicesOrder", b =>
                {
                    b.Property<int>("ServicesInquiryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ServicesInquiryID"));

                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ServicesDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Servicesstatus")
                        .HasColumnType("int");

                    b.HasKey("ServicesInquiryID");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("ServicesOrders");
                });

            modelBuilder.Entity("ProjectDataStructure.Electronics.ServicesProvider", b =>
                {
                    b.Property<int>("ProviderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProviderId"));

                    b.Property<string>("BusinessName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BusinessPhotoPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServiceYouProvide")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProviderId");

                    b.ToTable("ServicesProviders");
                });

            modelBuilder.Entity("ProjectDataStructure.Enum.ServicesType", b =>
                {
                    b.Property<int>("ServicesTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ServicesTypeId"));

                    b.Property<string>("ServiceType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ServicesTypeId");

                    b.ToTable("SerciesTypes");

                    b.HasData(
                        new
                        {
                            ServicesTypeId = 1,
                            ServiceType = "Plumbing"
                        },
                        new
                        {
                            ServicesTypeId = 2,
                            ServiceType = "Electricians"
                        });
                });

            modelBuilder.Entity("ProjectDataStructure.IdentityClass.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IndiaUserAddressAddressId")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ServicesProviderProviderId")
                        .HasColumnType("int");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("IndiaUserAddressAddressId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("ServicesProviderProviderId");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("ProjectDataStructure.Indiaclass.AutoMobile.ModelYear", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ModelYear");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            year = 2005
                        },
                        new
                        {
                            Id = 2,
                            year = 2006
                        },
                        new
                        {
                            Id = 3,
                            year = 2007
                        },
                        new
                        {
                            Id = 4,
                            year = 2008
                        },
                        new
                        {
                            Id = 5,
                            year = 2009
                        },
                        new
                        {
                            Id = 6,
                            year = 2010
                        },
                        new
                        {
                            Id = 7,
                            year = 2011
                        },
                        new
                        {
                            Id = 8,
                            year = 2012
                        },
                        new
                        {
                            Id = 9,
                            year = 2013
                        },
                        new
                        {
                            Id = 10,
                            year = 2014
                        },
                        new
                        {
                            Id = 11,
                            year = 2015
                        },
                        new
                        {
                            Id = 12,
                            year = 2016
                        },
                        new
                        {
                            Id = 13,
                            year = 2017
                        },
                        new
                        {
                            Id = 14,
                            year = 2018
                        },
                        new
                        {
                            Id = 15,
                            year = 2019
                        });
                });

            modelBuilder.Entity("ServicesProviderServicesType", b =>
                {
                    b.Property<int>("ServicesProvidersProviderId")
                        .HasColumnType("int");

                    b.Property<int>("ServicesTypesServicesTypeId")
                        .HasColumnType("int");

                    b.HasKey("ServicesProvidersProviderId", "ServicesTypesServicesTypeId");

                    b.HasIndex("ServicesTypesServicesTypeId");

                    b.ToTable("ServicesProviderServicesType");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ProjectDataStructure.IdentityClass.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ProjectDataStructure.IdentityClass.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProjectDataStructure.IdentityClass.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ProjectDataStructure.IdentityClass.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ProjectDataStructure.Addressrelatedclasses.IndiaUserAddress", b =>
                {
                    b.HasOne("ProjectDataStructure.Addressrelatedclasses.IndiaCity", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("ProjectDataStructure.Electronics.ServicesOrder", b =>
                {
                    b.HasOne("ProjectDataStructure.IdentityClass.ApplicationUser", "ApplicationUser")
                        .WithMany("servicesOrder")
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("ProjectDataStructure.IdentityClass.ApplicationUser", b =>
                {
                    b.HasOne("ProjectDataStructure.Addressrelatedclasses.IndiaUserAddress", "IndiaUserAddress")
                        .WithMany()
                        .HasForeignKey("IndiaUserAddressAddressId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ProjectDataStructure.Electronics.ServicesProvider", "ServicesProvider")
                        .WithMany()
                        .HasForeignKey("ServicesProviderProviderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("IndiaUserAddress");

                    b.Navigation("ServicesProvider");
                });

            modelBuilder.Entity("ServicesProviderServicesType", b =>
                {
                    b.HasOne("ProjectDataStructure.Electronics.ServicesProvider", null)
                        .WithMany()
                        .HasForeignKey("ServicesProvidersProviderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProjectDataStructure.Enum.ServicesType", null)
                        .WithMany()
                        .HasForeignKey("ServicesTypesServicesTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ProjectDataStructure.IdentityClass.ApplicationUser", b =>
                {
                    b.Navigation("servicesOrder");
                });
#pragma warning restore 612, 618
        }
    }
}
